### ISSUE TITLE
Make broom use some sort of fuel!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [CyclopsMC/EvilCraft#231]
I just started this game, and about 2 hours in I found a broom in a building defended by skelettons. (mod added structure).

Now I can fly around carefree....bit too early, too powerful in my opinion. I'd like to have to spent some sort of fuel for the broom to work.

Like blood maybe...?

**Comment by immortaleeb** [comment]
TL;DR: we had the same idea and the broom will probably completely change in one of the next updates.

Long version:
Ever since we added the broom we were actually planning on adding a proper way to craft it and making it fuel-powered was one of the ideas (we were also thinking blood).
I actually think that the next update will contain a complete overhaul of the broom as soon as the update to 1.8 is done, but I'll have to check with @rubensworks to be sure since I haven't really worked on the code in a long time.

**Comment by Blue64** [comment]
Also DEFINITELY make it WAY less common in the loot lol at one point I had 5 Brooms after only clearing 2 mob spawners and finding a village, and I didn't even find what I was out searching for (needed Sugar Canes, got lost in a Desert Biome lol) fortunately, thanks to some MineTweaker magic, I'll be able to smelt them down into `<liquid:blood>`, although I would prefer access to [`<liquid:life essence>`](https://github.com/WayofTime/BloodMagic/blob/master/src/main/java/WayofTime/alchemicalWizardry/common/LifeEssence.java#L24), but MineTweaker can't recognize white space for the LiquidDict (unless I figure out how to do [what they were talking about](https://github.com/stanhebben/MineTweaker3/issues/150#issuecomment-147843698) on the GitHub, [I've gotten zero help](https://github.com/stanhebben/MineTweaker3/issues/150#issuecomment-156790372)), but that's a different topic for a different mod(s)

**Comment by rubensworks** [comment]
@Blue64 Are you using the latest version of the mod? The spawning rates have been significantly reduced since last update.
Eventually, these won't appear in the looting chests anymore though, I'll implement a TCon-like crafting system for brooms, but that will be something for 1.8(.8).

Also, have you tried using `<liquid:life\ essence>` for your other problem?

**Comment by rubensworks** [comment]
So, I'm happy to say, that brooms have finally been reworked.
Release 0.10.0 contains fully modular and upgradable brooms, and they now run on blood.
I guess it's time to finally close this issue :)
